export const CODES = {
  // Authentication & Authorization
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_INVALID: "TOKEN_INVALID",
  TOKEN_MISSING: "TOKEN_MISSING",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",

  // User
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  USER_INACTIVE: "USER_INACTIVE",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",

  // Validation
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_PROVIDER: "INVALID_PROVIDER",

  // Server
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  BAD_REQUEST: "BAD_REQUEST",

  // Business Logic
  PERMISSION_DENIED: "PERMISSION_DENIED",

  // OAuth / Email Account
  OAUTH_REAUTH_REQUIRED: "OAUTH_REAUTH_REQUIRED",
  OAUTH_TOKEN_REVOKED: "OAUTH_TOKEN_REVOKED",

  SUCCESS: "SUCCESS",
} as const;

export type ErrorCode = (typeof CODES)[keyof typeof CODES];
